import pygame

pygame.mixer.init()
pygame.mixer.music.load('assets/metal.ogg')

shooting = pygame.mixer.Sound('assets/shotgun.ogg')
wave = pygame.mixer.Sound('assets/wave.ogg')

come_back = pygame.mixer.Sound('assets/come-back.ogg')
endangered = pygame.mixer.Sound('assets/endangered.ogg')
feeding_fish = pygame.mixer.Sound('assets/feeding-fish.ogg')
fish_music = pygame.mixer.Sound('assets/fish-music.ogg')
fisherman = pygame.mixer.Sound('assets/fisherman.ogg')
fishing = pygame.mixer.Sound('assets/fishing.ogg')
hobby = pygame.mixer.Sound('assets/hobby.ogg')
i_am_out = pygame.mixer.Sound('assets/i-am-out.ogg')
new_specie = pygame.mixer.Sound('assets/new-specie.ogg')
no_water = pygame.mixer.Sound('assets/no-water.ogg')
not_fair = pygame.mixer.Sound('assets/not-fair.ogg')
red_sea = pygame.mixer.Sound('assets/red-sea.ogg')
reload = pygame.mixer.Sound('assets/reload.ogg')
sign = pygame.mixer.Sound('assets/sign.ogg')

pygame.mixer.music.set_volume(0.3)
shooting.set_volume(0.1)
wave.set_volume(0.25)

come_back.set_volume(1.0)
endangered.set_volume(1.0)
feeding_fish.set_volume(1.0)
fish_music.set_volume(1.0)
fisherman.set_volume(1.0)
fishing.set_volume(1.0)
hobby.set_volume(1.0)
i_am_out.set_volume(1.0)
new_specie.set_volume(1.0)
no_water.set_volume(1.0)
not_fair.set_volume(1.0)
red_sea.set_volume(1.0)
reload.set_volume(1.0)
sign.set_volume(1.0)
